#!/bin/sh
# $Id$
# VOB: 09.10.2004
#set -x
#
error()
{
        logger -p user.err -t "${IDENT}[$$]" "error: $*"
        echo  "${IDENT}[$$]" "error: $*"
		exit 1
}
cd /home
for user in braun suzi
do
	DATE=`date +%Y-%m-%d.%H%M`
	TARBALL="/local/backup/${user}-daily-${DATE}.tar.bz"
	FLAG="/home/${user}/.dump-daily"
	#
	tar cvjf $TARBALL --newer=${FLAG}  ./${user}
	if [ $? = 0 ]
	then
		touch /home/${user}/.dump-daily
	fi
done
#EOF

