#!/bin/sh
#
# $Id: jet,v 1.2 1997/10/05 20:49:42 braun Exp $
#
# $Log: jet,v $
# Revision 1.2  1997/10/05 20:49:42  braun
# changed from dtpad to asedit.
#
# Revision 1.1  1997/10/05 20:47:22  braun
# Initial revision
#
#
# starts jetedit with the given file in background
# or asks to create an empty file with the given name
#
EDIT_TMP="/tmp/edit_$$"
MY_EDIT="/usr/X11R6/bin/asedit"
#
CREATE_FILE()
{
    if touch $1
    then
        chmod 664 $1
        echo "$1 wird angelegt!"
        ls -l $1
    else
        echo "$1 konnte nicht angelegt werden."
        exit 1
    fi   
}

if [ $# = 0 ]
then
    CREATE_FILE $EDIT_TMP
    $MY_EDIT $EDIT_TMP &
    echo "$EDIT_TMP wird geladen ..."
    exit 0
else
    for i in $*
        do
            if [ ! -f $i ]
            then
                echo "$i existiert nicht - neu anlegen? [j/n][Return]"
                read IN
                case $IN in
                    y | Y | j | J)	CREATE_FILE $i;;
                    *)              exit 0;;
                esac
            fi
            $MY_EDIT $i &
            echo "$i wird geladen ..."
        done
fi
exit 0
