#!/bin/sh
# convert Images to Thumbnails in the same format
set -x
#
GEOMETRY="120x120"
EXTENSION="jpg"
SUFFIX="_.${EXTENSION}"
#
for IMAGE in $*
do
	IMAGENAME=`basename ${IMAGE} .${EXTENSION}`
	/usr/X11R6/bin/convert -geometry ${GEOMETRY} ${IMAGE} ${IMAGENAME}.${SUFFIX}
done
#
exit 0
