#!/bin/sh
# Volker M. Braun, <volker.m.braun@gmx.de>
#
# $Id$
#
#
#
#set -x
##########################################
SOCKET="7777"
DOWNLOADS="/local/downloads"
###########################################
#
SCRIPT=`basename $0`
#
info()
{
   logger -t "${SCRIPT}[$$]" $*
}
error()
{
   logger -p user.err -t "${SCRIPT}[$$]" "ERROR: $*"
}
debug()
{
   logger -p user.debug -t "${SCRIPT}[$$]" $*
}
# make sure we are in our HOME directory
#
cd $DOWNLOADS
#
/home/braun/bin/unison.linux-text -socket $SOCKET -log -logfile /tmp/unison.log -owner braun &
#
exit 0
#
#EOF
