#!/bin/sh 
# module:         nsload
# version:        1.1
# last modify:    96/10/21 09:05:00
#
# @(#)nsload	1.1 96/10/21 09:05:00  , Volker Braun.
#
# remote document loader for Netscape
#
# Refer to http://home.netscape.com/newsref/std/x-remote.html for detailed description.
#
#set -x
MYNAME=`basename $0`
#
EXE=`which netscape`
# test if exe is available 
if [ ! -x $EXE ]
then
    echo "$MYNAME: Warning: $EXE not found!"
    exit 1
fi
#
USAGE()
{
    echo "Usage: $MYNAME [files-to-load]" 
}
#
if [ $# = 0 ]
then
    USAGE
fi
#
for i in $*
do
	if [ ! -f $i ]
	then
	    echo "$MYNAME: $i does not exist! :-("
	    exit 1
	fi    
	DIRNAME=`dirname $i`
	if [ `basename $i` = $i ]
	then  
	    DOCPATH=`pwd`/`basename $i` # $i has to be a filename in the current working directory
	else
	    DOCPATH=$i	# $i is an absolute pathname for the file
	fi
	if [ ! -r $DOCPATH ]
	then
	    echo "$MYNAME: $DOCPATH is not readable. :-("
	    exit 2
	fi
	echo "$MYNAME: remote open of $DOCPATH..." 
	$EXE -remote "openURL(file:$DOCPATH)"
done
exit 0

