#!/bin/sh 
# module:         play
# version:        1.1
# last modify:    96/08/14 11:37:14
#
# @(#)play	1.1 96/08/14 11:37:14  , Volker Braun.
#
#set -x
#exec >/tmp/$0.$$ 2>&1
#
MYNAME=`basename $0`
#
USAGE()
{
    echo "Usage:"
    echo
    echo "$MYNAME [Sun_audio_files]"
    echo
    echo "$MYNAME plays the [Sun_audio_files] via the /dev/audio." 
    echo
 
    exit 0
}
#
if [ $# = 0 ]
then
    USAGE
fi
#
for i in $*
do
	cat $i >/dev/audio
done
exit 0

