#!/bin/bash
# rsync mm-lab's external documents to my dropbox folder
#
DATE=`date +%Y-%m-%d_%H-%M-%S`
SOURCE="/cygdrive/c/Users/vbn/AppData/Local/Microsoft/Outlook/"
DESTINATION="/cygdrive/c/Users/vbn/Dropbox/Backup/mm0162/Outlook/"
LOG=$DESTINATION/$DATE.txt
EXCLUDES="*.tmp"
#
OUTPUT=`rsync.exe -av --delete --exclude="$EXCLUDES" "$SOURCE" "$DESTINATION"`
RET=$?
#
echo -e "$OUTPUT \nrsync exit with $RET at $DATE." > $LOG
exit 0
#EOF

